### ISSUE TITLE
Hi，when i read the code, i did not find the two component GMM which is used in cross-supervision with entropy regularization.

### ISSUE THREAD

**Issue by LanXiaoPang613** [Hzzone/TCL#2]
Hi，when i read the code, i did not find the two component GMM which is used in cross-supervision with entropy regularization. could you tell me. thank you very much!

**Comment by Hzzone** [comment]
https://github.com/Hzzone/TCL/blob/bf713d97d4504e0eb96c3e0affba837283af8129/models/tcl/tcl.py#L199

https://github.com/Hzzone/TCL/blob/bf713d97d4504e0eb96c3e0affba837283af8129/models/tcl/tcl_wrapper.py#L89

https://github.com/Hzzone/TCL/blob/bf713d97d4504e0eb96c3e0affba837283af8129/models/tcl/tcl_wrapper.py#L79

**Comment by erhuliu** [comment]
`context_assignments_logits = features.mm(centers.T) / opt.temp`

Why is this divided by the hyperparameter temp, instead of the variance in the paper?
