### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by ZhimaoPeng** [Hzzone/TCL#3]
With the following function , we get three augmented views of an image，it contains two strong augmentation and one weak augmentation in sequence:
        
`def ThreeCropTransform(img):  
      return TwoCropTransform(train_transform)(img) + [weak_transform(img), ]
`
But the image after loading is the following:    
`im_w, im_q, im_k = images`    
The weakly augmented image comes first, why is this?

**Comment by Hzzone** [comment]
Thanks for your careful reading! I will check it and fix this mistake later!

**Comment by Hzzone** [comment]
Fixed.
