### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_clustering'

### ISSUE THREAD

**Issue by erhuliu** [Hzzone/TCL#4]
Error when importing torch_clustering from models.basic_template.py, is this a custom package or a built-in package? I can't find either one, I hope you can give me an answer!

`import torch
import torchvision.datasets
from torchvision import transforms
import numpy as np
import torch.distributed as dist
import tqdm

from utils import TwoCropTransform, extract_features
from utils.ops import convert_to_cuda, is_root_worker, dataset_with_indices
from utils.grad_scaler import NativeScalerWithGradNormCount
from utils.loggerx import LoggerX
import torch_clustering`

**Comment by Hzzone** [comment]
https://github.com/Hzzone/TCL/issues/1
I will fix this confusion later.
